### PR TITLE
Dryer's DNA dataset should have proper parameter names

### PR DESCRIPTION
**Pull request by haspelmath**
Dryer's DNA dataset should have proper parameter names

### CODE REVIEW

**Comment by xrotwang** [comment]
Following the [cldfbench philosophy](https://github.com/cldf/cldfbench/blob/master/README.md#overview) such additional information (in addition to what the author of the source data provided) should go into [`etc/parameters.csv`](https://github.com/cldf-datasets/dryerorder/blob/master/etc/parameters.csv) from where it can be picked up when [writing the CLDF data](https://github.com/cldf-datasets/dryerorder/blob/65248b1eed650717b83dd08905fdf1602c4669be/cldfbench_dryerorder.py#L51-L55).

**Comment by xrotwang** [comment]
I'll do that in a new PR here, then close this one.

**Comment by haspelmath** [comment]
OK, but "what the author provided" is not a fully fixed concept. Dryer has a 150-page PDF document (part of the supplementary materials for the journal), but he provided some additional information in personal exchanges with me. And the parameter names would definitely be checked by him.

**Comment by xrotwang** [comment]
Yes, I guess such a situation will be common, too. The `raw/` and `etc/` setup is important, though, for scenarios, where the author keeps working on the data independent of the repository, so changes in `raw/` might be overwritten with each synchronisation.

**Comment by johenglisch** [comment]
see #11

**Pull request closed without merging**
